### PR TITLE
Tests for annotations with fields

### PR DESCRIPTION
**Pull request by szarnekow**
See https://github.com/eclipse/xtext-eclipse/issues/436

### CODE REVIEW

**Comment by cdietrich** [comment]
where is the actual impl?

**Comment by szarnekow** [comment]
https://github.com/eclipse/xtext-eclipse/pull/437/files#diff-4f301154bd2d13be046848f7f52bc3be

**Comment by cdietrich** [comment]
but there are test failures in extras on your branch

**Comment by szarnekow** [comment]
Fixed

**Pull request merged**
