### PR TITLE
Ignore default methods from superclass branch when checking ambiguous inherited methods.

### PR DESCRIPTION
**Pull request by gallandarakhneorg**
This patch fixes an incomplete coverage of JLS 8.4.8
(https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.8).
Overriding conflicts were detected between interfaces from the direct
superclass branch and a direct superinterface. It is not compliant with
the JLS and the current behavior of javac.

Complete unit tests are is [Xtend PR 192](https://github.com/eclipse/xtext-xtend/pull/192).

see https://github.com/eclipse/xtext/issues/2296
see https://github.com/eclipse/xtext-xtend/pull/192

Signed-off-by: Stéphane Galland <galland@arakhne.org>

### CODE REVIEW

**Comment by szarnekow** [comment]
Did you try to play with `org.eclipse.xtext.xbase.typesystem.override.ResolvedFeatures.handleOverridesAndConflicts(JvmOperation, Multimap<String, AbstractResolvedOperation>)`, e.g. line 361 ( https://github.com/eclipse/xtext-extras/blob/master/org.eclipse.xtext.xbase/src/org/eclipse/xtext/xbase/typesystem/override/ResolvedFeatures.java#L361 ) where we could pass true instead of false? Would that make a difference for your usecase?

**Comment by gallandarakhneorg** [comment]
Changing within the original code only the value of the argument from `false` to `true` does not solve the issue. Output error is: `The type A inherits multiple implementations of the method spliterator() from Iterable and Set.` The conflicting `Iterable` comes from the `AbstractCollection` inheritance branch.

Reminder of the tested code:
```xtend
import java.util.Iterator
import java.util.Set
import java.util.AbstractCollection
class A<T> extends AbstractCollection<T> implements Set<T> {
  override Iterator<T> iterator {
    null
  }
  override int size {
    0
  }
}
```
According to my interpretation of JLS: `Set` should provides the default implementation for `splititerator` because it a direct super type of that provides this default implementation. And, in fact, javac does not fail on this code.

**Comment by szarnekow** [comment]
Understood. So what is missing in the current impl is the concept of a direct supertype. Are there other references to it in the JLS?

**Comment by gallandarakhneorg** [comment]
I think it is more related to the difference between the superclass inheritance and superinterface inheritance than the concept of "direct" super type. I have written the patch according to this point of view. I think the key sentence is "[It is a compile-time error if a class C inherits a default method whose signature is override-equivalent with another method inherited by C, unless there exists an abstract method declared in a superclass of C and inherited by C that is override-equivalent with the two methods.](https://docs.oracle.com/javase/specs/jls/se8/html/jls-8.html#jls-8.4.8.4)" I have not found a clear statement within thr JLS regarding the observed behavior of javac, except in this section and Section 8.4.8. If you find better explanation, please give me back.

It may be interesting to write a systematic test bench of all possible cases, and compare the answers of javac and Xtend.

**Comment by szarnekow** [comment]
> It may be interesting to write a systematic test bench of all possible cases, and compare the answers of javac and Xtend.

Would you have the time to do that?

**Comment by gallandarakhneorg** [comment]
Under process: I have a first script generating more than 8000 unit tests.

**Comment by szarnekow** [comment]
Hey @gallandarakhneorg, did you make more progress on this ticket?

**Comment by gallandarakhneorg** [comment]
Yes. But, it is still not finish (validated of the generated test coverage). I may provide inputs for next week.

**Comment by gallandarakhneorg** [comment]
I have a script that creates 8747 unit tests related to different inheritance cases.
Because I'm using Xtend for creating the tests, I think this project is not the best place to put them.
Should I request a pull in Xtend project? Or is another way to use Xtend for tests within xtext-extras?

**Comment by szarnekow** [comment]
That sounds great. Yes, you are right, these tests should be put into the Xtend unit test suites, if they use the Xtend language to test the inheritance / override validation.

**Comment by gallandarakhneorg** [comment]
Ok, I'm validating my generated unit tests on my own DSL, which includes Xtend, in order to detect the failures and fix the minor things. Then, I will request a pull to Xtend project and give the reference within this discussion.

**Comment by szarnekow** [comment]
That's a sound plan. 👍 Very good! Thank you for the effort!

**Comment by gallandarakhneorg** [comment]
Unit tests are discussed within https://github.com/eclipse/xtext-xtend/pull/192

**Comment by cdietrich** [comment]
i assume this branch and the test branch both need a rebase

**Comment by szarnekow** [comment]
I'm not sure how to proceed with the effort that was spent on this issue.

**Comment by cdietrich** [comment]
move to 2.24

**Comment by cdietrich** [comment]
this repository has been merged/moved to https://github.com/eclipse/xtext.
please feel free to recreate this PR against that repository in case it still is relevant.

**Pull request closed without merging**
