### PR TITLE
[Bug 420984] Adapted compiler to generate only used variables.

### PR DESCRIPTION
**Pull request by ArneDeutsch**
Add test cases for new code generation cases.

Change-Id: Ia3becba790b2cad6f8c874d750d443609aa2e956
Signed-off-by: Arne Deutsch <arne@idedeluxe.com>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=420984

**Comment by cdietrich** [comment]
please fix 

- org.eclipse.xtext.xbase.tests.compiler.output.CompilerTraceTest

**Comment by cdietrich** [comment]
There are Failures in the Xtext-Xtend Repo as well: http://services.typefox.io/open-source/jenkins/job/xtext-xtend/job/ArneDeutsch%252Fbug-420984/

**Comment by ArneDeutsch** [comment]
Adapted all failing tests.

**Comment by cdietrich** [comment]
https://github.com/eclipse/xtext-xtend/pull/337/

**Pull request merged**
