### PR TITLE
[493784] Clean JvmTypeChangeDispatcher when discarding derived state

### PR DESCRIPTION
**Pull request by kthoms**
Recreated PR eclipse/xtext-extras#82 due to problems on the build server for branch name containing /
see http://services.typefox.io/open-source/jenkins/job/xtext-extras/job/cd%252Fbug493784/2/console

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=493784

**Comment by svenefftinge** [comment]
The underyling problem is that we do not clear the adapterlist when derived jvmtypyes get proxified

**Comment by svenefftinge** [comment]
PR https://github.com/eclipse/xtext-extras/pull/86 would be my preferred fix.

**Comment by kthoms** [comment]
So #86 makes this one obsolete?

**Comment by svenefftinge** [comment]
Let me add a test, but then yes.

**Comment by kthoms** [comment]
Would this test help you?
https://github.com/eclipse/xtext-xtend/pull/103/commits/286a65c918d50f1c616358ad9d219aa86b357b5b

**Comment by svenefftinge** [comment]
I will try to do it more locally in xbase.tests, but we can keep that, too.

**Comment by svenefftinge** [comment]
merged #86 instead

**Pull request closed without merging**
