### PR TITLE
[#261] Implemented a Binary Class Lookup Cache for Java Sources

### PR DESCRIPTION
**Pull request by cdietrich**
[#261] Implemented a Binary Class Lookup Cache for Java Sources
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
this is just a pull request to discuss possible solutions for #261 
@szarnekow would be nice if we could have a look somewhen next week

**Comment by cdietrich** [comment]
still the question: how can this be performance and function tested locally.

**Comment by szarnekow** [comment]
My mac file system is case sensitive when it matters and case insensitive in general. So functional testing was already done. Regarding perf tests - I'm still thinking about a different approach that would avoid the double check on all class files. But that is not yet green.

**Comment by cdietrich** [comment]
TODO: cache the ibinarytype and not the answers

**Pull request closed without merging**
