### PR TITLE
fix for inner class issue in IndexedJvmTypeAccess + ASM. Fixes #30

### LINKED ISSUE #30: [ASM] IncrementalBuilder with JavaLanguage does not work with Inner Classes
Having a Java Class like

```
package mypack;
public class FakeIssue60GrammarAccess {
	
	private final GreetingElements pGreeting;
	
	public FakeIssue60GrammarAccess() {
		this.pGreeting = new GreetingElements();
	}
	
	public class GreetingElements {

		public String getHelloKeyword_0() { return null; }
		
	}
	
	public GreetingElements getGreetingAccess() {
		return pGreeting;
	}

}	
```

and a Xtend class like

```
package mypack

import mypack.FakeIssue60GrammarAccess$GreetingElements

class Demo {
	
	extension mypack.FakeIssue60GrammarAccess
	
	GreetingElements elements

	def void format() {
		greetingAccess.helloKeyword_0
		println(elements)
	}
	
}
```

then the compilation with the incremental builder e.g. xtend-gradle-plugin fails with `ERROR:The method getGreetingAccess() from the type FakeIssue60GrammarAccess refers to the missing type Object `

see https://github.com/xtext/xtext-gradle-plugin/issues/60

### PR DESCRIPTION
**Pull request by cdietrich**
fix for inner class issue in IndexedJvmTypeAccess + ASM. Fixes #30

Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
for tests see https://github.com/eclipse/xtext-xtend/pull/36 as well

**Comment by svenefftinge** [comment]
Is there a reason you want to keep two different implementations?

**Comment by cdietrich** [comment]
i just want to have to flexibility to change the impl for a while

**Comment by cdietrich** [comment]
removed array based impl

**Comment by svenefftinge** [comment]
+1

**Pull request merged**
