### PR TITLE
Kt xtend issue942 suppress modifiers

### PR DESCRIPTION
**Pull request by kthoms**

### CODE REVIEW

**Comment by tivervac** [comment]
@kthoms CI does not agree with you

**Comment by kthoms** [comment]
> @kthoms CI does not agree with you

What do you mean? The build is green. What problem does CI have?

**Comment by tivervac** [comment]
Hmm, it was red before, weird

**Comment by cdietrich** [comment]
I restarted the build
It failed cause concurrent run with xtext core

**Comment by kthoms** [comment]
@szarnekow Fine for you?

**Comment by szarnekow** [comment]
Nice improvement.

**Pull request merged**
