### PR TITLE
Copy non-UI related test classes from .xbase.junit to .xbase.testing

### LINKED ISSUE #100: Copy other classes from .xbase.junit into .xbase.testing
I think that classes that do not deal with the UI in .xbase.junit should be copied into .xbase.testing, e.g., org.eclipse.xtext.xbase.junit.evaluation.AbstractXbaseEvaluationTest and org.eclipse.xtext.xbase.junit.typesystem.TypeSystemSmokeTester.

This way we can deprecate those classes in .xbase.junit

(related to https://github.com/eclipse/xtext-eclipse/issues/155)

### PR DESCRIPTION
**Pull request by LorenzoBettini**
Additional notes:

xbase.junit was re-exporting xbase, while .xbase.testing did not re-export xbase (now it exports that).

I improved the error message in org.eclipse.xtext.xbase.testing.CompilationTestHelper.Result.getSingleGeneratedCode() when no files were generated.

What's left to be decided is whether to make .xbase.testing dependent on .xbase.testdata; currently the "testdata" directory in .xbase.testing is a subset of the one in .xbase.testdata 

Closes #100

### CODE REVIEW

**Comment by LorenzoBettini** [comment]
Please review

**Comment by spoenemann** [comment]
I've never worked with xbase.junit, so I'd like someone else to review. @svenefftinge?

**Comment by LorenzoBettini** [comment]
I forgot to mention that in my computer I ported the domainmodel example to use the copied classes instead of the deprecated ones; I still haven't pushed such modifications since they're in a different repository, xtext-eclipse

**Comment by LorenzoBettini** [comment]
@svenefftinge could you please have a look?

**Comment by LorenzoBettini** [comment]
I'd like to have this in Xtext 2.11.0

**Comment by cdietrich** [comment]
+1

**Comment by svenefftinge** [comment]
I'm also ok with adding it to 2.11

**Pull request merged**
