### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by Bananeweizen**

### CODE REVIEW

**Comment by cdietrich** [comment]
is it ok for you if i simply fix it?

**Comment by cdietrich** [comment]
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=498340 as well

**Comment by cdietrich** [comment]
pushed https://github.com/eclipse/xtext-extras/commit/dd8dff684e324fe435505992ec3aed7c98ed634a

**Comment by Bananeweizen** [comment]
Thanks, Christian. I typically select the "allow edits by project maintainers" checkbox to indicate that anyone can take over my work for further changes (even without asking), but I have never seen how that is actually reflected for you as project member in the UI of a pull request.

**Pull request closed without merging**
