### PR TITLE
make tests runnable with java 15 and 16

### PR DESCRIPTION
**Pull request by cdietrich**
make tests runnable with java 15 and 16
Signed-off-by: Christian Dietrich <christian.dietrich@itemis.de>

### CODE REVIEW

**Comment by cdietrich** [comment]
ReusedTypeProviderTest > testMemberCount_16 and other testMemberCount_16 are still failing.
Looks like Enums are compiled differently with Java 15
@szarnekow any idea?

**Comment by szarnekow** [comment]
When we compile xbase.testdata with compliance level 11 or newer, there is no synthetic constructor in being generated.
Probably because nestmates allow to access the real stuff now without synthetic bridges.

**Comment by cdietrich** [comment]
ok i propose to leave the tests as is right now and just to commit the fixes i have done

**Review by szarnekow — APPROVED** [review]
Agreed

**Pull request merged**
