### PR TITLE
Kth/issue57

### PR DESCRIPTION
**Pull request by kthoms**

### CODE REVIEW

**Comment by spoenemann** [comment]
Why have you added tests to the testlanguages project? (Bug462047LangParsingTest, ContentAssistFragmentTestLangParsingTest, XImportSectionTestLangParsingTest) Shouldn't all tests be in the xbase.tests project?

**Comment by kthoms** [comment]
The mentioned tests were added by the code generator. The JUnitFragment2 produces a ParsingTest for each language by default.

**Comment by kthoms** [comment]
Eclipse specific changes are handled in eclipse/xtext-eclipse#93

**Comment by cdietrich** [comment]
@kthoms this is obsolte correct?

**Comment by cdietrich** [comment]
will redo this with https://github.com/eclipse/xtext-extras/issues/175

**Pull request closed without merging**
