### PR TITLE
[493784] Clean JvmTypeChangeDispatcher when discarding derived state

### PR DESCRIPTION
**Pull request by kthoms**
Reapplied changes from eclipse/xtext#1044 for new repository structure

Signed-off-by: Karsten Thoms <karsten.thoms@itemis.de>

### CODE REVIEW

**Comment by eclipsewebmaster** [comment]
Issue tracker reference:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=493784

**Comment by kthoms** [comment]
@svenefftinge In eclipse/xtext#104 this question was open:

> what is our cleanup strategy for type resources

Please advice.

**Comment by svenefftinge** [comment]
I think you missed an important piece of the original change. The clean up method is never called.

**Comment by kthoms** [comment]
Updated.

**Comment by svenefftinge** [comment]
that was fast :)

**Comment by svenefftinge** [comment]
Did the tests in xtend succeed before the last change already?

**Comment by kthoms** [comment]
Replaced by #83

**Pull request closed without merging**
